import { ClassDetail } from "../components/class-list/class-list.component";

export enum ClassTypes {
  cubs = "cubs",
  juniors = "juniors",
  adults = "adults",
}

export enum DaysOfTheWeek {
  monday = "Monday",
  tuesday = "Tuesday",
  wednesday = "Wednesday",
  thursday = "Thursday",
  friday = "Friday",
  saturday = "Saturday",
  sunday = "Sunday",
}

export const classesData: ClassDetail[] = [
  {
    id: 1,
    start: "1830",
    end: "2030",
    type: ClassTypes.adults,
    classLength: "120",
    dayOfWeek: DaysOfTheWeek.monday,
  },
  {
    id: 2,
    start: "1100",
    end: "1300",
    type: ClassTypes.adults,
    classLength: "120",
    dayOfWeek: DaysOfTheWeek.tuesday,
  },
  {
    id: 3,
    start: "1600",
    end: "1645",
    type: ClassTypes.cubs,
    classLength: "45",
    dayOfWeek: DaysOfTheWeek.wednesday,
  },
  {
    id: 4,
    start: "1645",
    end: "1745",
    type: ClassTypes.juniors,
    classLength: "60",
    dayOfWeek: DaysOfTheWeek.wednesday,
  },
  {
    id: 5,
    start: "1800",
    end: "1900",
    type: ClassTypes.adults,
    classLength: "60",
    dayOfWeek: DaysOfTheWeek.wednesday,
  },
  {
    id: 6,
    start: "1900",
    end: "2100",
    type: ClassTypes.adults,
    classLength: "120",
    dayOfWeek: DaysOfTheWeek.wednesday,
  },
  {
    id: 7,
    start: "1100",
    end: "1300",
    type: ClassTypes.adults,
    classLength: "120",
    dayOfWeek: DaysOfTheWeek.thursday,
  },
  {
    id: 8,
    start: "1830",
    end: "2030",
    type: ClassTypes.adults,
    classLength: "120",
    dayOfWeek: DaysOfTheWeek.thursday,
  },
  {
    id: 9,
    start: "1830",
    end: "2030",
    type: ClassTypes.adults,
    classLength: "120",
    dayOfWeek: DaysOfTheWeek.friday,
  },
  {
    id: 10,
    start: "1100",
    end: "1300",
    type: ClassTypes.adults,
    classLength: "120",
    dayOfWeek: DaysOfTheWeek.saturday,
  },
  {
    id: 11,
    start: "0930",
    end: "1015",
    type: ClassTypes.cubs,
    classLength: "45",
    dayOfWeek: DaysOfTheWeek.sunday,
  },
  {
    id: 12,
    start: "1015",
    end: "1115",
    type: ClassTypes.juniors,
    classLength: "60",
    dayOfWeek: DaysOfTheWeek.sunday,
  },
  {
    id: 13,
    start: "1130",
    end: "1300",
    type: ClassTypes.adults,
    classLength: "90",
    dayOfWeek: DaysOfTheWeek.sunday,
  },
];
